[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

monitor_speed = 115200

build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1     ; Ensures Serial logging works over the native USB port
    -D DRADIOLIB_DEBUG_PROTOCOL=1

lib_deps =
    jgromes/RadioLib @ ^7.7.1        ; Installs the matching RadioLib core engine
    bblanchon/ArduinoJson @ ^6.21.3  ; Handles downlink payload json structures
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0
    jgromes/RadioBoards @ ^1.0.0